services:
  database-postgres:
    image: postgres:17
    container_name: 10x-series-matcher-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - 10x-series-matcher-pgdata:/var/lib/postgresql/data

volumes:
  10x-series-matcher-pgdata:
